name: Fetch Pharmacy Data

on:
  schedule:
    - cron: '0 11 * * *'  # Her gün saat 11:00'de (UTC)
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu checkout et
        uses: actions/checkout@v3

      - name: Node.js kur (18.x)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: NPM bağımlılıklarını yükle
        run: npm ci

      - name: Yüklenen paketleri listele (debug için)
        run: npm list --depth=1

      - name: node-fetch yüklü mü kontrol et
        run: node -p "require.resolve('node-fetch')"

      - name: Veriyi çek (update-eczaneler.js çalıştır)
        run: node scripts/update-eczaneler.js
        env:
          COLLECTAPI_KEY: ${{ secrets.COLLECTAPI_KEY }}
