name: Update Pharmacy Data Daily

on:
  schedule:
    - cron: '*/5 * * * *' # Her 5dk
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Puppeteer dependencies
        run: sudo apt-get install -y libxss1 libappindicator1 libindicator7 libasound2 libatk-bridge2.0-0 libgtk-3-0

      - name: Run scraper
        run: node scripts/update-eczaneler.js

      - name: Commit scraped data
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add public/data/eczaneler.json
          git commit -m "Güncel eczane verisi" || echo "No changes"
          git push