name: Günlük Nöbetçi Eczane Verisi Çek

on:
  workflow_dispatch: # Manuel tetikleme için Gerekli (Run Workflow butonu çıkar)
  schedule:
    - cron: '0 5 * * *' # Her gün sabah 08:00'de (UTC+3 için 5)

jobs:
  update-eczaneler:
    runs-on: ubuntu-latest

    steps:
      - name: Reposuyu klonla
        uses: actions/checkout@v3

      - name: Node.js kurulumu
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Bagimlilik yukle
        run: npm install

      - name: .env dosyasa ayarla
        run: |
          echo "COLLECTAPI_KEY=${{ secrets.COLLECTAPI_KEY }}" >> .env

      - name: Veriyi güncelle
        run: node scripts/update-eczaneler.js

      - name: Güncellenen verileri push et
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "📦 Eczane verisi güncellendi [bot]" || echo "Değişiklik yok"
          git push
