name: Fetch Pharmacy Data

on:
  schedule:
    - cron: '0 9 * * *'  # Her sabah 09:00'de çalışır
  workflow_dispatch:      # Manuel tetikleme için buton sağlar

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Debug current directory
        run: |
          echo "Current directory:"
          pwd
          echo "Listing all files recursively:"
          ls -R .

      - name: Check if node-fetch is installed
        run: |
          echo "Checking for node-fetch:"
          npm ls node-fetch || true

      - name: Run data fetch script
        run: node scripts/update-eczaneler.js
        env:
          COLLECTAPI_KEY: ${{ secrets.COLLECTAPI_KEY }}
