name: Fetch Pharmacy Data Daily

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Create .env file from secret
        run: echo "COLLECTAPI_KEY=${{ secrets.COLLECTAPI_KEY }}" > .env

      - name: Run scraper script
        run: node scripts/update-pharmacy-data.js

      - name: Commit updated data
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add public/data/pharmacies.json
          git commit -m "Update pharmacy data"
          git push
