name: Update Pharmacy Data Daily

on:
  schedule:
    - cron: '*/5 * * * *'  # her 5 dakikada bir çalışır
  workflow_dispatch:       # manuel tetikleme için

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: node scripts/update-eczaneler.js
