name: Günlük Eczane Verisi Güncelle

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'  # UTC 08:00 = Türkiye saati ile 11:00

jobs:
  fetch-and-save-data:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: 🧾 Repositoriesi çek
        uses: actions/checkout@v3

      - name: 🔧 Node.js kurulumu
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Bağımlılıkları kur (npm ci)
        run: npm ci

      - name: 📂 Debug: node_modules dizininde node-fetch var mı?
        run: ls -R node_modules | grep node-fetch || echo_
